name: Code checks my bot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install python
        user: actions/setup-python@v2
        with:
          python-version: 3.11.0

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-isort mypy
          pip install -r requirements.txt
      - name: Run flake8
        run: flake8 .
      - name: Run mypy
        run: mypy .